spring:
  profiles: 
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abalasu1/spring-config.git   
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles}
---
spring:
  profiles: dev
  
server:
  port: 8888
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true     
---
spring:
  profiles: prod
  
server:
  port: 9888
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true  